# Scripts-level makefile for BNL Genome sequence utilities package
#
# $Id: Makefile,v 0.2 2003/01/19 13:33:46 mccorkle Exp mccorkle $
#

include  ../Config/config.mak
include  ../header.mak

#PERLS      = bundle_lanes compare connected_subgraphs gc_cont fasta2phd \
#             gb2bnl gb2fasta mum2tv poly_a pqual qhplot qfix re2tv seq_len \
#             sings2ace grpp nmers rna2dna sel subseqs gsts truncseq \
#             split-tags clust-tags raw2fasta neighbors dimers trimers \
#             tetramers frag  ptt2tv rna2tv glimm2tv signals recode ic icplot \
#             whsolu sigs2tv re sagediff splt rc prox ditags orfs.pl trans.pl \
#             numseqs

PERLS      = compare connected_subgraphs gc_cont fasta2phd \
             gb2bnl gb2fasta poly_a pqual qhplot qfix seq_len \
             sings2ace grpp nmers rna2dna sel subseqs gsts truncseq \
             split-tags clust-tags raw2fasta dimers trimers \
             tetramers frag  signals recode ic icplot \
             whsolu  re sagediff splt rc prox ditags orfs.pl trans.pl \
             numseqs


SRCS       = $(PERLS) Makefile
BINS       = $(PERLS)


all:






