#!/usr/bin/perl
# rctest - check rc
#           run ranseq a bunch of times with random min and max lengths
#           run rc on the result, and rc back and make sure sequences
#           are the same

$n_reps = 1000;                  # run this many checks

$orig_file  = "/tmp/rctest_orig.$$";
$rc_file    = "/tmp/rctest_rc.$$";
$rcrc_file    = "/tmp/rctest_rcrc.$$";

for ( $i = 0; $i < $n_reps; $i++ )
   {
    print "$i\n" unless ( $i % 100 );

    $a = int( rand( 1000 ) );
    $b = $a + int( rand( 1000 ) );
    $rs_cmd = "../ranseq -a $a -b $b >$orig_file";
    #print "$rs_cmd\n";
    system( "$rs_cmd" );
    $rc_cmd = "../rc $orig_file >$rc_file";    
    #print "$rc_cmd\n";
    system( "$rc_cmd" );
    $rc_cmd = "../rc $rc_file >$rcrc_file";    
    #print "$rc_cmd\n";
    system( "$rc_cmd" );
    $diff = "diff $orig_file $rcrc_file";
    #print "$diff\n";
    system( $diff );
   }

#unlink( $orig_file, $rc_file, $rcrc_file );

