#!/usr/bin/perl
# Program:     extract_sequences_list
# Programmer:  Sean R. McCorkle
#              Biological, Environmental and Climate Sciences Dept.
#              Brookhaven National Laboratory
# Language:    perl
# 
# Description: Reads a list of identifiers from a file, one per line.
#              Then passes any fasta sequences whose headers start with
#              any of those ids (assuming the id is the first whitespace
#              separated entry on the header).
#              
# Usage:       extract_sequences_list  <wanted_list>  [seqs...]
#


use strict;

my %want = get_list( (shift) );

my $pass = 0;

while ( <> )
   {
    next if ( /^\s*$/ );
    if ( /^>(\S+)+/ )
       { $pass = $want{$1}; }
    print if ( $pass );
   }


sub  get_list
   {
    my $file = shift;
    my %w = ();

    open( LIST, $file ) || die "Can't open $file: $!\n";
    while ( $_ = <LIST> )
       {
        chomp;
        s/^\s*//;
        s/\s*$//;
        $w{$_}++;
       }
    close( LIST );

    return( %w );
   }
