#!/usr/bin/perl
# Program:      seq_len
# Programmer:   Sean R. McCorkle, 
#               Biology Department, Brookhaven National Laboratory
# Language:     perl
# Description:  reads fasta-format DNA or protein sequences, prints out 
#               their length (in nt or amino acids)
# 
# Usage:        seq_len [-tT] [<seq> ...] 
#
#               (stdin used if nothing specified)
#
# Options:       -t   terse output - print one sequence length number per line
#                -T   total        - print total count only
#
# $Id: seq_len,v 0.2 2003/02/11 22:02:58 mccorkle Exp mccorkle $
#

use  Getopt::Std;

select( ( select(STDOUT), $| = 1 )[0] );
select( ( select(STDERR), $| = 1 )[0] );

die "bad option\n" unless ( getopts( 'tT' ) );

$count = 0;
$total = 0;
while( <> )
   {
    chomp;
    if ( s/^\>// )
        {
         output_line() if ( defined( $heading ) && ! $opt_T );
         $heading = $_ ? $_ : " ";
         $total += $count;
         $count = 0;
        }
    elsif( /^;/ )
        { next; }
    else
        { 
         s/\s+//g;
         s/^\d*//;
         $count += length( $_ );
        }
   }

#if ( $count )
if ( defined( $heading ) )
   {
    output_line() unless ( $opt_T );
    $total += $count;
   }

print "$total\n" if ( $opt_T );

sub output_line
   {
    printf "%10d ", $count;
    print "$heading" unless ( $opt_t );
    print "\n";
   }
