trie:  trie.o  io.o
	cc -o $@ trie.o io.o


hairpins:  hairpins.o  io.o  suffixtree.o
	cc -o $@ hairpins.o io.o suffixtree.o


stsearch:  stsearch.o  io.o  suffixtree.o
	cc -o $@ stsearch.o io.o suffixtree.o

